# Generated by Django 3.0.3 on 2020-03-14 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='masterdate',
            field=models.DateField(default=datetime.date.today, unique=True),
        ),
    ]
