# Generated by Django 3.0.3 on 2020-03-14 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200314_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinout',
            name='date_worked',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
