# Generated by Django 3.0.3 on 2020-03-14 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200314_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masterdate', models.DateField(default=datetime.date.today, unique=True)),
            ],
        ),
    ]
