# Generated by Django 3.0.3 on 2020-03-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200315_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinout',
            name='overtime_e',
            field=models.TimeField(blank=True, null=True, verbose_name='残業終了'),
        ),
        migrations.AlterField(
            model_name='checkinout',
            name='overtime_s',
            field=models.TimeField(blank=True, null=True, verbose_name='残業開始'),
        ),
    ]
