# Generated by Django 3.0.3 on 2020-03-18 08:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200315_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinout',
            name='date_worked',
            field=models.ForeignKey(default=datetime.datetime.today, on_delete=django.db.models.deletion.PROTECT, to='app.Date', verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='date',
            name='masterdate',
            field=models.DateField(default=datetime.datetime.today, unique=True, verbose_name='日付'),
        ),
    ]
