# Generated by Django 3.0.3 on 2020-03-18 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200318_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='masterdate',
            field=models.DateTimeField(default=datetime.datetime.today, unique=True, verbose_name='日付'),
        ),
    ]
