# Generated by Django 3.0.3 on 2020-03-18 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200318_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='masterdate',
            field=models.DateField(default=datetime.datetime.today, unique=True, verbose_name='日付'),
        ),
    ]
