# Generated by Django 3.0.3 on 2020-03-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200318_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinout',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True, verbose_name='出勤時刻'),
        ),
        migrations.AlterField(
            model_name='checkinout',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退勤時刻'),
        ),
        migrations.AlterField(
            model_name='checkinout',
            name='overtime_e',
            field=models.DateTimeField(blank=True, null=True, verbose_name='残業終了'),
        ),
        migrations.AlterField(
            model_name='checkinout',
            name='overtime_s',
            field=models.DateTimeField(blank=True, null=True, verbose_name='残業開始'),
        ),
    ]
