# Generated by Django 3.0.3 on 2020-03-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200320_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinout',
            name='total_overtime',
            field=models.IntegerField(blank=True, null=True, verbose_name='残業時間合計'),
        ),
    ]
